# Use a base Python image
FROM python:3.10.12-slim

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code and mlruns folder
COPY . .

# Expose port 5000
EXPOSE 5000

# Command to run the app
CMD ["python", "app.py"]

# Add this step to install dependencies from the requirements.txt generated by MLflow
COPY mlruns/0/0/329f09c3c0324af79f00cecbd57f4fc2/artifacts/model/requirements.txt ./model_requirements.txt
RUN pip install --no-cache-dir -r model_requirements.txt

RUN pip install pandas==2.2.2 psutil==5.9.5 scipy==1.13.1
